networks:
  docker-sock:
    external: true

services:
  docker.sock-proxy:
    hostname: docker.sock-proxy
    image: padhihomelab/docker.sock-proxy:${DOCKER_SOCK_PROXY_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - docker-sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      # For querying labels etc.
      CONTAINERS: '1'
      # For Traefik network events
      EVENTS: '1'
      TZ: ${TZ:?}
