messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} stats may now be accessed on
      ${_LINK_FONT_}https://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTPS_MONITOR_PORT}/${DOCKER_SOCK_PROXY_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
