services:
  qbittorrent:
    image: padhihomelab/qbittorrent-nox:${QBITTORRENT_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true
    tty: true

    network_mode: container:vpn
    volumes:
    - ./data/qbittorrent/config:/config:rw
    - ./data/qbittorrent/data:/data:rw
    - ./data/qbittorrent/torrents/complete:/torrents/complete:rw
    - ./data/qbittorrent/torrents/incomplete:/torrents/incomplete:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
