version: '2.4'

services:
  caddy:
    hostname: caddy
    image: caddy:2.5.1
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - i2p

    volumes:
    - ./config/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "wget", "-qSO", "/dev/null", "http://localhost:2019/config"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  i2p:
    hostname: i2p
    image: padhihomelab/i2p:1.8.0
    restart: unless-stopped

    volumes:
    - ./data/i2p/i2p/.i2p:/i2p/.i2p
    - ./data/i2p/i2psnark:/i2psnark

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
