services:
  mqtt:
    logging:
      options:
        max-size: "1m"
        max-file: "1"
  postgres:
    logging:
      options:
        max-size: "1m"
        max-file: "1"
  teslamate:
    logging:
      options:
        max-size: "4m"
        max-file: "1"
