services:
  teslamate:
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.${TESLAMATE_TRAEFIK_NAMESPACE:?}.loadBalancer.server.port=4000"
    #
    - "traefik.http.middlewares.strip-prefix-for-${TESLAMATE_TRAEFIK_NAMESPACE:?}.stripPrefix.prefixes=/${TESLAMATE_BASE_PATH:?}"
    #
    - "traefik.http.routers.${TESLAMATE_TRAEFIK_NAMESPACE:?}.rule=Host(`${SERVER_LAN_FQDN:?}`) && PathPrefix(`/${TESLAMATE_BASE_PATH:?}`)"
    - "traefik.http.routers.${TESLAMATE_TRAEFIK_NAMESPACE:?}.entryPoints=lan-https-monitor"
    - "traefik.http.routers.${TESLAMATE_TRAEFIK_NAMESPACE:?}.middlewares=strip-prefix-for-${TESLAMATE_TRAEFIK_NAMESPACE:?}"
