services:
  teslamate:
    labels:
      traefik.enable: true
      traefik.http.middlewares.strip-teslamate-prefix.stripPrefix.prefixes: "/teslamate"
      traefik.http.middlewares.only-https-forwarded-proto.headers.customRequestHeaders.X-Forwarded-Proto: https
      traefik.http.middlewares.only-wss-forwarded-proto.headers.customRequestHeaders.X-Forwarded-Proto: wss
      traefik.http.routers.teslamate.rule: PathPrefix(`/teslamate`)
      traefik.http.routers.teslamate.entryPoints: lan-https
      traefik.http.routers.teslamate.middlewares: strip-teslamate-prefix, only-https-forwarded-proto
      traefik.http.routers.teslamate-websocket.rule: PathPrefix(`/teslamate/live/websocket`)
      traefik.http.routers.teslamate-websocket.entryPoints: lan-https
      traefik.http.routers.teslamate-websocket.middlewares: strip-teslamate-prefix, only-wss-forwarded-proto
