listen_addresses = ['0.0.0.0:8053']
max_clients = 256

server_names = []

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = false

require_dnssec = true
require_nolog = true
require_nofilter = true

disabled_server_names = []

force_tcp = false
http3 = false

timeout = 4096
keepalive = 30

lb_strategy = 'p2'
lb_estimator = true

log_level = 2
log_file = '/dev/stdout'

cert_refresh_delay = 240

bootstrap_resolvers = ['9.9.9.9:53', '1.1.1.1:53']
ignore_system_dns = true

netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'

block_ipv6 = true
block_unqualified = true
block_undelegated = true

reject_ttl = 60

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 30
cache_neg_max_ttl = 300


[sources]

  ## A fast subset of the default source list from https://github.com/DNSCrypt/dnscrypt-resolvers

  [sources.'fast-public-resolvers']
    urls = ['https://raw.githubusercontent.com/padhi-homelab/services/master/pihole/extra/dnscrypt-proxy/resolvers.md']
    cache_file = 'fast-public-resolvers.md'
    minisign_key = 'RWSBkxsy0yTPu4nZqV3A629dKOsPMygTmW1ipw8XUPteuEaw4klYfBGd'
    prefix = 'fast-'

  ## Default source list from https://github.com/DNSCrypt/dnscrypt-resolvers

  #[sources.'public-resolvers']
  #  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
  #  cache_file = 'public-resolvers.md'
  #  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  #  prefix = ''

  ## OpenNIC servers - https://www.opennic.org/

  #[sources.opennic-resolvers]
  #  urls = ['https://download.dnscrypt.info/dnscrypt-resolvers/v3/opennic.md']
  #  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  #  cache_file = 'opennic-resolvers.md'
  #  prefix = 'opennic-'

  ## Anonymized DNS relays

  #[sources.'relays']
  #  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
  #  cache_file = 'relays.md'
  #  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  #  refresh_delay = 72
  #  prefix = ''


[broken_implementations]

fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cisco-sandbox', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']


[anonymized_dns]

skip_incompatible = false
