services:
  postgres:
    logging:
      options:
        max-size: "1m"
        max-file: "1"
  redis:
    logging:
      options:
        max-size: "1m"
        max-file: "1"
  netbox:
    logging:
      options:
        max-size: "4m"
        max-file: "1"
