services:
  hass:
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.${HASS_TRAEFIK_NAMESPACE:?}.loadBalancer.server.port=8123"
    #
    # FIXME: Serving hass behind a subpath is not supported, yet.
    # See https://github.com/home-assistant/core/issues/21113
    #
    - "traefik.http.routers.${HASS_TRAEFIK_NAMESPACE:?}.rule=Host(`${SERVER_WAN_FQDN:?}`) && PathPrefix(`/`)"
    - "traefik.http.routers.${HASS_TRAEFIK_NAMESPACE:?}.entryPoints=wan-https-service-exclusive"
