version: '2.4'

services:
  hass:
    hostname: hass
    image: padhihomelab/hass:2022.2.9_1.23.0
    restart: unless-stopped

    volumes:
    - ./data/hass/config:/config:rw

    #devices:
    #- /dev/ttyUSB0:/dev/ttyUSB0
    #- /dev/ttyACM0:/dev/ttyACM0

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
