version: '2.4'

services:
  hass:
    hostname: hass
    image: padhihomelab/hass:2022.9.4_1.27.2
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    volumes:
    - ./data/hass/config:/config:rw

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}

    logging:
      options:
        max-size: "8m"
        max-file: "4"
