version: '2.4'

services:
  hass:
    hostname: hass
    image: padhihomelab/hass:2023.6.2_1.32.1
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    volumes:
    - ./data/hass/config:/config:rw
    - ./data/hass/media:/media:rw

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
