version: '2.4'

networks:
  proxy:
    external: true

services:
  hass:
    hostname: hass
    image: padhihomelab/hass:2024.4.4_1.34.0
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/hass/config:/config:rw
    - ./data/hass/media:/media:rw
    # NOTE: Necessary for bluetooth integration
    - /run/dbus:/run/dbus:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
