networks:
  proxy:
    external: true

services:
  hass:
    hostname: hass
    image: padhihomelab/hass:2024.12.1_2.0.1
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/hass/config:/config:rw
    - ./data/hass/media:/media:rw
    # NOTE: Necessary for bluetooth integration
    - /run/dbus:/run/dbus:ro
    # NOTE: Patch to show raw states for iRobot devices
    - ./config/hass/etc/cont-init.d/99_patch-iRobot.sh:/etc/cont-init.d/99_patch-iRobot.sh:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
