services:
  mariadb:
    hostname: mariadb
    image: mariadb:11.5.2
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: ${USER_ID:?}

    volumes:
    - ./config/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    - ./data/mariadb/var/lib/mysql:/var/lib/mysql

    environment:
      MARIADB_ROOT_PASSWORD: 'kodi_db_mariadb_root_password'

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 3
