services:
  certbot:
    hostname: certbot
    image: certbot/certbot:${CERTBOT_VERSION:?}
    restart: unless-stopped
    entrypoint: entrypoint

    security_opt:
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    volumes:
    - ./config/certbot/usr/local/bin/entrypoint:/usr/local/bin/entrypoint:ro
    - ./config/certbot/usr/local/bin/healthcheck:/usr/local/bin/healthcheck:ro
    - ./data/certbot/etc/letsencrypt:/etc/letsencrypt:rw
    - ./data/certbot/var/lib/letsencrypt:/var/lib/letsencrypt:rw
    - ./data/certbot/var/log/letsencrypt:/var/log/letsencrypt:rw

    environment:
      CERTBOT_EMAIL: ${LETS_ENCRYPT_ACME_EMAIL:?}
      CERTBOT_DOMAIN: ${SERVER_WAN_FQDN:?}
      CERTBOT_EXTRA_FLAGS:
      TZ: ${TZ:?}

    healthcheck:
      test: "healthcheck"
      interval: 1m
      start_period: 60s
