services:
  certbot:
    hostname: certbot
    image: padhihomelab/certbot:3.0.1
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    volumes:
    - ./data/certbot/etc/letsencrypt:/etc/letsencrypt

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
      CERTBOT_EMAIL: ${SERVER_LETS_ENCRYPT_ACME_EMAIL:?}
      CERTBOT_DOMAIN: ${SERVER_WAN_FQDN:?}
      CERTBOT_EXTRA_FLAGS: ${CERTBOT_EXTRA_FLAGS}
