version: '2.4'

services:
  certbot:
    hostname: certbot
    image: padhihomelab/certbot:1.31.0
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    volumes:
    - ./data/certbot/etc/letsencrypt:/etc/letsencrypt

    environment:
      TZ: ${TZ:?}
      CERTBOT_EMAIL: ${SERVER_LETS_ENCRYPT_ACME_EMAIL:?}
      CERTBOT_DOMAIN: ${SERVER_WAN_FQDN:?}
      CERTBOT_EXTRA_FLAGS: ${CERTBOT_EXTRA_FLAGS}

    logging:
      options:
        max-size: "64m"
        max-file: "8"
