accessLog:
  bufferingSize: 32
  fields:
    defaultMode: drop
    names:
      Duration: keep
      RouterName: keep
      ServiceName: keep
      ClientAddr: keep
      RequestAddr: keep
      RequestPath: keep
      RequestProtocol: keep
      RequestScheme: keep
      RequestContentSize: keep
      OriginStatus: keep
      DownstreamStatus: keep
      Overhead: keep
      RetryAttempts: keep
      TLSVersion: keep
    headers:
      defaultMode: drop
      names:
        Referer: keep
        User-Agent: keep
  format: json

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  lets-encrypt:
    acme:
      email: ${SERVER_LETS_ENCRYPT_ACME_EMAIL}
      storage: "/etc/traefik/lets-encrypt/acme.json"
      caServer: ${SERVER_LETS_ENCRYPT_ACME_CA_SERVER}
      tlsChallenge: true

entryPoints:
  internal:
    address: ":8080"
  lan-http:
    address: ":9080"
    http:
      middlewares:
      - lan-ip-whitelist@file
      - compress-response@file
      - security-headers@file
  lan-https:
    address: ":9443"
    http:
      middlewares:
      - lan-ip-whitelist@file
      - compress-response@file
      - security-headers@file
      - ssl-headers@file
      tls: true
  wan-https:
    address: ":443"
    http:
      middlewares:
      - compress-response@file
      - security-headers@file
      - ssl-headers@file
      tls:
        certResolver: lets-encrypt
        domains:
        - main: ${SERVER_WAN_FQDN}

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  format: json
  level: INFO

ping:
  entryPoint: internal

providers:
  docker:
    endpoint: "tcp://docker.sock-proxy:1279"
    exposedByDefault: false
    network: proxy
    watch: true
  file:
    directory: "/dynamic"
    watch: true

serversTransport:
  insecureSkipVerify: true
