api:
  dashboard: true
  insecure: false

entryPoints:
  internal:
    address: ":8080"
  lan-http:
    address: ":9080"
    http:
      middlewares:
      - lan-ip-whitelist@file
  lan-https:
    address: ":9443"
    http:
      middlewares:
      - lan-ip-whitelist@file
      tls: true
  wan-https:
    address: ":443"
    http:
      tls: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ping:
  entryPoint: internal

providers:
  docker:
    endpoint: "tcp://docker.sock-proxy:1279"
    exposedByDefault: false
    watch: true
  file:
    directory: "/dynamic"
    watch: true

serversTransport:
  insecureSkipVerify: true
