version: '2.4'

networks:
  default:

services:
  caddy:
    hostname: caddy
    image: caddy:2.4.6
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - jackett
    - radarr
    - sonarr
  
    volumes:
    - ./config/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "wget", "-qSO", "/dev/null", "http://localhost:2019/config"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  jackett:
    hostname: jackett
    image: padhihomelab/jackett:0.20.504
    restart: unless-stopped

    volumes:
    - ./data/jackett/config:/config:rw
    - ./data/jackett/downloads:/downloads:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

  lidarr:
    hostname: lidarr
    image: padhihomelab/lidarr:1.0.0.2458
    restart: unless-stopped

    volumes:
    - ./data/lidarr/config:/config:rw
    - ./data/lidarr/downloads:/downloads:rw
    - ./data/radarr/music:/music:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

  radarr:
    hostname: radarr
    image: padhihomelab/radarr:4.0.4.5922
    restart: unless-stopped

    volumes:
    - ./data/radarr/config:/config:rw
    - ./data/radarr/downloads:/downloads:rw
    - ./data/radarr/movies:/movies:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

  sonarr:
    hostname: sonarr
    image: padhihomelab/sonarr:3.0.6.1342
    restart: unless-stopped

    volumes:
    - ./data/sonarr/config:/config:rw
    - ./data/sonarr/downloads:/downloads:rw
    - ./data/sonarr/tv:/tv:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
