networks:
  traefik-net:
    external: true

services:
  gitea:
    hostname: gitea
    image: gitea/gitea:${GITEA_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true
    user: "${USER_ID:?}:${GROUP_ID}"

    networks:
    - traefik-net
    volumes:
    - ./data/gitea/var/lib/gitea:/var/lib/gitea:rw
    - ./data/gitea/etc/gitea:/etc/gitea:rw

    environment:
      RUN_CROND: 1
      BACKUP_INTERNAL: 7d
      BACKUP_RETENTION: 30d
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "curl", "-o", "/dev/null", "-sS", "http://localhost:3000/api/healthz"]
      interval: 15s
      timeout: 2s
      start_period: 5s
