version: '2.4'

networks:
  proxy:
    external: true

services:
  gitea:
    hostname: gitea
    image: gitea/gitea:1.21.10-rootless
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: ${USER_ID:?}

    networks:
    - proxy
    volumes:
    - ./data/gitea/var/lib/gitea:/var/lib/gitea:rw
    - ./data/gitea/etc/gitea:/etc/gitea:rw

    environment:
      RUN_CROND: 1
      BACKUP_INTERNAL: 7d
      BACKUP_RETENTION: 30d
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "curl", "-o", "/dev/null", "-sS", "http://localhost:3000/healthcheck"]
      interval: 15s
      timeout: 2s
      start_period: 5s
