messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} may now be accessed on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_SERVICE_PORT}/${GITEA_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
