messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} may now be available on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_INTERNAL_PORT_EXCLUSIVE}/${_RESET_FONT_}
    - >-
      ${_THIS_COMPOSITION_} SMTP server now be available on
      ${_LINK_FONT_}tcp://${SERVER_LAN_FQDN}:${NTFY_SMTP_LISTEN_PORT}/${_RESET_FONT_}
    - >-
      ${_THIS_COMPOSITION_} UI may now be accessed on
      ${_LINK_FONT_}https://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTPS_INTERNAL_PORT_EXCLUSIVE}/${NTFY_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
