networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29
  traefik-net:
    external: true

services:
  dnscrypt-proxy:
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:${DNSCRYPT_PROXY_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
      default:
        ipv4_address: 10.0.0.3
    volumes:
    - ./config/dnscrypt-proxy/etc/dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}

  pihole:
    hostname: pihole
    image: pihole/pihole:${PIHOLE_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    depends_on:
      dnscrypt-proxy:
        condition: service_healthy

    networks:
      default:
        ipv4_address: 10.0.0.4
      traefik-net:
    volumes:
    - ./data/pihole/etc/pihole:/etc/pihole:rw
    - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    environment:
      FTLCONF_dns_upstreams: '10.0.0.3#8053'
      FTLCONF_dns_bogusPriv: 'true'
      FTLCONF_dns_domainNeeded: 'true'
      FTLCONF_dns_listeningMode: all
      FTLCONF_webserver_api_password: admin
      PIHOLE_UID: ${USER_ID:?}
      PIHOLE_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}
