services:
  pihole:
    labels:
      traefik.enable: true
      traefik.http.services.pihole.loadBalancer.server.port: 80
      #
      traefik.http.middlewares.strip-pihole-prefix.stripPrefix.prefixes: "/${PIHOLE_BASE_PATH:?}"
      traefik.http.middlewares.add-admin-prefix.addPrefix.prefix: "/admin"
      #
      traefik.http.routers.pihole.rule: Host(`${SERVER_LAN_FQDN:?}`) && PathPrefix(`/${PIHOLE_BASE_PATH:?}`)
      traefik.http.routers.pihole.entryPoints: lan-https-svc
      traefik.http.routers.pihole.middlewares: strip-pihole-prefix, add-admin-prefix
      #
      # FIXME: The rule below is necessary to correctly redirect after login.
      # The `/admin` redirect seems to be hard coded (unlike the rest of the application, thankfully!).
      #
      traefik.http.routers.pihole-admin.rule: Host(`${SERVER_LAN_FQDN:?}`) && Path(`/admin/`)
      traefik.http.routers.pihole-admin.entryPoints: lan-https-svc
      traefik.http.routers.pihole-admin.service: pihole@docker
      traefik.http.middlewares.pihole-postlogin-redirect.redirectRegex.permanent: true
      traefik.http.middlewares.pihole-postlogin-redirect.redirectRegex.regex: "^https://(.+)/admin/(.*)$"
      traefik.http.middlewares.pihole-postlogin-redirect.redirectRegex.replacement: "https://$${1}/${PIHOLE_BASE_PATH:?}/$${2}"
      traefik.http.routers.pihole-admin.middlewares: pihole-postlogin-redirect@docker
