services:
  pihole:
    ports:
    # FIXME: For DNS resolution from other containers on the SAME machine,
    # SERVER_IP needs to be explicitly specified.
    # see https://stackoverflow.com/a/69994721/554436
    - ${SERVER_IP:?}:53:53/tcp
    - ${SERVER_IP:?}:53:53/udp
