services:
  pihole:
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.${PIHOLE_TRAEFIK_NAMESPACE:?}.loadBalancer.server.port=80"
    #
    # FIXME: Serve over a basepath
    #
    - "traefik.http.routers.${PIHOLE_TRAEFIK_NAMESPACE:?}.rule=Host(`${SERVER_LAN_FQDN:?}`)"
    - "traefik.http.routers.${PIHOLE_TRAEFIK_NAMESPACE:?}.entryPoints=lan-https-internal-exclusive"
