services:
  pihole:
    labels:
      traefik.enable: true
      traefik.http.services.pihole.loadBalancer.server.port: 80
      #
      # FIXME: Serve over a basepath
      #
      traefik.http.routers.pihole.rule: Host(`${SERVER_LAN_FQDN:?}`)
      traefik.http.routers.pihole.entryPoints: lan-https-internal-exclusive
