version: "2.4"

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29
  proxy:
    external: true

services:
  dnscrypt-proxy:
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.1.2
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
      default:
        ipv4_address: 10.0.0.3
    volumes:
    - ./config/dnscrypt-proxy/etc/dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}

    logging:
      options:
        max-size: "2m"
        max-file: "1"

  pihole:
    hostname: pihole
    image: pihole/pihole:2022.09
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    # no `user:` needed; runs as non-root user since 2022.01

    depends_on:
    - dnscrypt-proxy

    networks:
      default:
        ipv4_address: 10.0.0.4
      proxy:
    volumes:
    - ./data/pihole/etc/pihole:/etc/pihole:rw
    - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    dns:
    - 10.0.0.4
    - 127.0.0.1
    environment:
      PIHOLE_DNS_: '10.0.0.3#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      SKIPGRAVITYONBOOT: 'true'
      CUSTOM_CACHE_SIZE: 50000
      WEBPASSWORD: admin
      TZ: ${TZ:?}

    logging:
      options:
        max-size: "8m"
        max-file: "4"
