version: "2.4"

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29

services:
  caddy:
    hostname: caddy
    image: caddy:2.5.2
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - pihole
  
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    volumes:
    - ./config/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "wget", "-qSO", "/dev/null", "http://localhost:2019/config"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  dnscrypt-proxy:
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.1.1
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
    - ./config/dnscrypt-proxy/etc/dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}

  pihole:
    hostname: pihole
    image: pihole/pihole:2022.07.1
    restart: unless-stopped
    # Runs as non-root user, as of 2022.01

    depends_on:
    - dnscrypt-proxy

    networks:
      pihole_net:
        ipv4_address: 10.0.0.4
    volumes:
    - ./data/pihole/etc/pihole:/etc/pihole:rw
    - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    cap_add:
    - NET_BIND_SERVICE
    dns:
    - 10.0.0.4
    - 127.0.0.1
    environment:
      PIHOLE_DNS_: '10.0.0.3#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      SKIPGRAVITYONBOOT: 'true'
      CUSTOM_CACHE_SIZE: 50000
      WEBPASSWORD: admin
      TZ: ${TZ:?}
