services:
  pihole:
    labels:
      traefik.enable: true
      traefik.http.middlewares.strip-pihole-prefix.stripPrefix.prefixes: "/pihole"
      traefik.http.middlewares.add-admin-prefix.addPrefix.prefix: "/admin"
      traefik.http.routers.pihole.rule: PathPrefix(`/pihole`)
      traefik.http.services.pihole.loadBalancer.server.port: 80
      traefik.http.routers.pihole.entryPoints: lan-https
      traefik.http.routers.pihole.middlewares: strip-pihole-prefix, add-admin-prefix
