version: "2.4"

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29
  proxy:
    external: true

services:
  dnscrypt-proxy:
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.1.2
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
    - ./config/dnscrypt-proxy/etc/dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}

  pihole:
    hostname: pihole
    image: pihole/pihole:2022.07.1
    restart: unless-stopped
    # Runs as non-root user, as of 2022.01

    depends_on:
    - dnscrypt-proxy

    networks:
      pihole_net:
        ipv4_address: 10.0.0.4
      proxy:
    volumes:
    - ./data/pihole/etc/pihole:/etc/pihole:rw
    - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    dns:
    - 10.0.0.4
    - 127.0.0.1
    environment:
      PIHOLE_DNS_: '10.0.0.3#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      SKIPGRAVITYONBOOT: 'true'
      CUSTOM_CACHE_SIZE: 50000
      WEBPASSWORD: admin
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.middlewares.strip-pihole-prefix.stripPrefix.prefixes: "/pihole"
      traefik.http.middlewares.add-admin-prefix.addPrefix.prefix: "/admin"
      traefik.http.routers.pihole.rule: PathPrefix(`/pihole`)
      traefik.http.services.pihole.loadBalancer.server.port: 80
      traefik.http.routers.pihole.entryPoints: lan-https
      traefik.http.routers.pihole.middlewares: strip-pihole-prefix, add-admin-prefix
