networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29
  proxy:
    external: true

services:
  dnscrypt-proxy:
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.1.5
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
      default:
        ipv4_address: 10.0.0.3
    volumes:
    - ./config/dnscrypt-proxy/etc/dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}

  pihole:
    hostname: pihole
    image: pihole/pihole:2024.07.0
    restart: unless-stopped

    # FIXME: cannot use `no-new-privileges` yet,
    # see https://discourse.pi-hole.net/t/sudo-suid-problems/20590
    # security_opt:
    # # NOTE: Do NOT add a [space] before `true` below.
    # - no-new-privileges:true
    # NOTE: no `user:` needed; runs as non-root user since 2022.01

    depends_on:
      dnscrypt-proxy:
        condition: service_healthy

    networks:
      default:
        ipv4_address: 10.0.0.4
      proxy:
    volumes:
    - ./data/pihole/etc/pihole:/etc/pihole:rw
    - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    dns:
    - 10.0.0.4
    - 127.0.0.1
    environment:
      PIHOLE_DNS_: '10.0.0.3#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      SKIPGRAVITYONBOOT: 'true'
      CUSTOM_CACHE_SIZE: 50000
      WEBPASSWORD: admin
      TZ: ${TZ:?}
