services:
  solvarr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    network_mode: container:vpn
    volumes:
    - ./config/solvarr/healthcheck.sh:/healthcheck.sh:ro

    environment:
      DOCKER_UID: ${USER_ID:?}
      GROUP_UID: ${GROUP_ID:?}
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      start_period: 15s

  jackett:
    image: padhihomelab/jackett:${JACKETT_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    network_mode: container:vpn
    volumes:
    - ./data/jackett/config:/config:rw
    - ./data/jackett/downloads:/downloads:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}
