version: '2.4'

networks:
  proxy:
    external: true

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.6.8
    restart: unless-stopped

    cap_add:
    - NET_ADMIN
    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/openvpn/config:/config:ro

    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'

  solvarr:
    image: flaresolverr/flaresolverr:v3.3.13
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    depends_on:
    - openvpn

    network_mode: service:openvpn

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

  jackett:
    image: padhihomelab/jackett:0.21.1585
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    depends_on:
    - openvpn
    - solvarr

    network_mode: service:openvpn
    volumes:
    - ./data/jackett/config:/config:rw
    - ./data/jackett/downloads:/downloads:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
