version: '2.4'

services:
  jackett:
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.rule: PathPrefix(`/${JACKETT_BASE_PATH:?}`)
      traefik.http.services.jackett.loadBalancer.server.port: 9117
      traefik.http.routers.jackett.entryPoints: wan-https
