version: '2.4'

networks:
  proxy:
    external: true

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.5.6

    networks:
    - proxy
    volumes:
    - ./data/openvpn/config:/config:ro

    cap_add:
    - NET_ADMIN
    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'

  jackett:
    image: padhihomelab/jackett:0.20.1680
    restart: unless-stopped

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
    - ./data/jackett/config:/config:rw
    - ./data/jackett/downloads:/downloads:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.jackett.rule: PathPrefix(`/jackett`)
      traefik.http.services.jackett.loadBalancer.server.port: 9117
      traefik.http.routers.jackett.entryPoints: wan-https
