messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_}:jackett may now be accessed on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_PORT}/${JACKETT_BASE_PATH}/${_RESET_FONT_}

pre_reqs:
- openvpn

related:
- traefik
