messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_}:jackett may now be accessed on
      ${_LINK_FONT_}https://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTPS_SERVICE_PORT}/${JACKETT_BASE_PATH}/${_RESET_FONT_}

pre_req:
- openvpn

related:
- traefik
