services:
  navidrome:
    labels:
      traefik.enable: true
      #
      traefik.http.routers.navidrome.rule: Host(`${SERVER_WAN_FQDN:?}`) && PathPrefix(`/${NAVIDROME_BASE_PATH:?}`)
      traefik.http.routers.navidrome.entryPoints: wan-https-service
