networks:
  traefik-net:
    external: true

services:
  navidrome:
    hostname: navidrome
    image: deluan/navidrome:${NAVIDROME_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    networks:
    - traefik-net
    volumes:
    - ./data/navidrome/music:/music:ro
    - ./data/navidrome/data:/data:rw

    environment:
      ND_BASEURL: "/${NAVIDROME_BASE_PATH:?}"
      ND_LOGLEVEL: info
      ND_SCANNER_SCHEDULE: 30m
      ND_SESSIONTIMEOUT: 8h
      TZ: ${TZ:?}
