version: '2.4'

networks:
  proxy:
    external: true

services:
  navidrome:
    hostname: navidrome
    image: deluan/navidrome:sha-13bb6c9
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    networks:
    - proxy
    volumes:
    - ./data/navidrome/music:/music:ro
    - ./data/navidrome/data:/data:rw

    environment:
      ND_BASEURL: /navidrome
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 30m
      ND_SESSIONTIMEOUT: 8h
      TZ: ${TZ:?}

    logging:
      options:
        max-size: "8m"
        max-file: "2"
