version: '2.4'

networks:
  proxy:
    external: true

services:
  navidrome:
    hostname: navidrome
    image: deluan/navidrome:sha-e981ee2
    restart: unless-stopped
    user: ${USER_ID:?}

    networks:
    - proxy
    volumes:
    - ./data/navidrome/music:/music:ro
    - ./data/navidrome/data:/data:rw

    environment:
      ND_BASEURL: /navidrome
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 30m
      ND_SESSIONTIMEOUT: 8h
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.navidrome.rule: PathPrefix(`/navidrome`)
      traefik.http.routers.navidrome.entryPoints: wan-https
