networks:
  proxy:
    external: true

services:
  navidrome:
    hostname: navidrome
    image: deluan/navidrome:0.53.3
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: ${USER_ID:?}

    networks:
    - proxy
    volumes:
    - ./data/navidrome/music:/music:ro
    - ./data/navidrome/data:/data:rw

    environment:
      ND_BASEURL: /navidrome
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 30m
      ND_SESSIONTIMEOUT: 8h
      TZ: ${TZ:?}
