services:
  traefik:
    labels:
    - "traefik.enable=true"
    #
    - "traefik.http.middlewares.strip-prefix-for-${TRAEFIK_OWN_NAMESPACE:?}.stripPrefix.prefixes=/${TRAEFIK_UI_BASE_PATH:?}"
    - "traefik.http.middlewares.add-dashboard-prefix-for-${TRAEFIK_OWN_NAMESPACE:?}.addPrefix.prefix=/${TRAEFIK_UI_BASE_PATH:?}/dashboard"
    #
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-api.rule=Host(`${SERVER_LAN_FQDN:?}`) && PathPrefix(`/${TRAEFIK_UI_BASE_PATH:?}/api`)"
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-api.entryPoints=lan-https-monitor"
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-api.service=api@internal"
    #
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-dashboard.rule=Host(`${SERVER_LAN_FQDN:?}`) && PathPrefix(`/${TRAEFIK_UI_BASE_PATH:?}`)"
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-dashboard.entryPoints=lan-https-monitor"
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-dashboard.service=api@internal"
    - "traefik.http.routers.${TRAEFIK_OWN_NAMESPACE:?}-dashboard.middlewares=strip-prefix-for-${TRAEFIK_OWN_NAMESPACE:?},add-dashboard-prefix-for-${TRAEFIK_OWN_NAMESPACE:?}"
