networks:
  docker-sock:
    external: true
  traefik-net:
    external: true

services:
  traefik:
    hostname: traefik
    image: traefik:${TRAEFIK_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true
    user: "${USER_ID:?}:${GROUP_ID}"

    networks:
    - docker-sock
    - traefik-net
    volumes:
    - ./config/traefik/dynamic:/dynamic:ro
    - ./generated/traefik/traefik.yml:/traefik.yml:ro
    - ./data/traefik/cert:/cert:ro

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 15s
      timeout: 2s
      start_period: 5s
