services:
  traefik:
    ports:
    # HTTP bindings intended for LAN exposure
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTP_SERVICE_PORT:?}:${SERVER_LAN_HTTP_SERVICE_PORT:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTP_SERVICE_PORT_EXCLUSIVE:?}:${SERVER_LAN_HTTP_SERVICE_PORT_EXCLUSIVE:?}
    # HTTPS bindings intended for LAN exposure
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_INTERNAL_PORT:?}:${SERVER_LAN_HTTPS_INTERNAL_PORT:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_INTERNAL_PORT_EXCLUSIVE:?}:${SERVER_LAN_HTTPS_INTERNAL_PORT_EXCLUSIVE:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_MONITOR_PORT:?}:${SERVER_LAN_HTTPS_MONITOR_PORT:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_MONITOR_PORT_EXCLUSIVE:?}:${SERVER_LAN_HTTPS_MONITOR_PORT_EXCLUSIVE:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_SERVICE_PORT:?}:${SERVER_LAN_HTTPS_SERVICE_PORT:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_SERVICE_PORT_EXCLUSIVE:?}:${SERVER_LAN_HTTPS_SERVICE_PORT_EXCLUSIVE:?}
    # HTTPS binding intended for WAN exposure
    - ${SERVER_WAN_BINDING_IP:?}:${SERVER_WAN_HTTPS_MONITOR_PORT:?}:${SERVER_WAN_HTTPS_MONITOR_PORT:?}
    - ${SERVER_WAN_BINDING_IP:?}:${SERVER_WAN_HTTPS_MONITOR_PORT_EXCLUSIVE:?}:${SERVER_WAN_HTTPS_MONITOR_PORT_EXCLUSIVE:?}
    - ${SERVER_WAN_BINDING_IP:?}:${SERVER_WAN_HTTPS_SERVICE_PORT:?}:${SERVER_WAN_HTTPS_SERVICE_PORT:?}
    - ${SERVER_WAN_BINDING_IP:?}:${SERVER_WAN_HTTPS_SERVICE_PORT_EXCLUSIVE:?}:${SERVER_WAN_HTTPS_SERVICE_PORT_EXCLUSIVE:?}
