services:
  traefik:
    ports:
    # Traefik internal dashboard & API
    - ${SERVER_LAN_BINDING_IP:?}:34443:34443
    # HTTP and HTTPS bindings intended for LAN exposure
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTP_PORT_A:?}:${SERVER_LAN_HTTP_PORT_A:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_PORT_A:?}:${SERVER_LAN_HTTPS_PORT_A:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTP_PORT_B:?}:${SERVER_LAN_HTTP_PORT_B:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_PORT_B:?}:${SERVER_LAN_HTTPS_PORT_B:?}
    # HTTPS binding intended for WAN exposure
    - ${SERVER_WAN_BINDING_IP:?}:${SERVER_WAN_HTTPS_PORT:?}:${SERVER_WAN_HTTPS_PORT:?}
