services:
  traefik:
    ports:
    - ${SERVER_LAN_BINDING_IP:?}:34443:34443
    - ${SERVER_WAN_BINDING_IP:?}:${SERVER_WAN_HTTPS_PORT:?}:${SERVER_WAN_HTTPS_PORT:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTP_PORT:?}:${SERVER_LAN_HTTP_PORT:?}
    - ${SERVER_LAN_BINDING_IP:?}:${SERVER_LAN_HTTPS_PORT:?}:${SERVER_LAN_HTTPS_PORT:?}
