networks:
  shared:
    external: true
  proxy:
    external: true

services:
  traefik:
    hostname: traefik
    image: traefik:v3.2.3
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: ${USER_ID:?}

    networks:
    - shared
    - proxy
    volumes:
    - ./config/traefik/dynamic:/dynamic:ro
    - ./generated/traefik/traefik.yml:/traefik.yml:ro
    - ./data/traefik/cert:/cert:ro

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 15s
      timeout: 2s
      start_period: 5s
