version: '2.4'

networks:
  proxy:
    external: true

services:
  docker.sock-proxy:
    hostname: docker.sock-proxy
    image: padhihomelab/docker.sock-proxy:2.6.2
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - default
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      CONTAINERS: '1'
      EVENTS: '1'
      TZ: ${TZ:?}

  traefik:
    hostname: traefik
    image: traefik:v2.8.3
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}
  
    depends_on:
    - docker.sock-proxy

    networks:
    - default
    - proxy
    volumes:
    - ./config/traefik/dynamic:/dynamic:ro
    - ./config/traefik/traefik.yml:/traefik.yml:ro
    - ./data/traefik/cert:/cert:ro
    - ./data/traefik/etc/traefik:/etc/traefik:rw
    - ./data/traefik/var/log/traefik:/var/log/traefik:rw

    environment:
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.dashboard.rule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      traefik.http.routers.dashboard.entryPoints: lan-https
      traefik.http.routers.dashboard.service: api@internal

    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 15s
      timeout: 2s
      start_period: 5s
