version: '2.4'

services:
  traefik:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.dashboard.rule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      traefik.http.routers.dashboard.entryPoints: lan-https
      traefik.http.routers.dashboard.service: api@internal
