version: '2.4'

networks:
  default:

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.5.2

    networks:
    - default
    volumes:
    - ./data/openvpn/config:/config:ro

    cap_add:
    - NET_ADMIN
    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'
      TZ: ${TZ:?}

  tor:
    image: padhihomelab/tor:0.4.5.9
    restart: unless-stopped

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
      - ./data/tor/etc/tor:/etc/tor:rw
      - ./data/tor/var/lib/tor:/var/lib/tor:rw
      - ./data/tor/var/log/tor:/var/log/tor:rw
  
    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}
