networks:
  traefik-net:
    external: true

services:
  mariadb:
    hostname: mariadb
    image: mariadb:${MARIADB_VERSION:?}
    restart: unless-stopped

    command: |-
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --innodb-file-per-table=1
      --skip-innodb-read-only-compressed
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

    security_opt:
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    networks:
    - default
    volumes:
    - ./data/mariadb/var/lib/mysql:/var/lib/mysql:rw

    env_file:
    - env/mariadb
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1

    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 15s
      start_period: 30s

  valkey:
    hostname: valkey
    image: valkey/valkey:${VALKEY_VERSION:?}
    restart: unless-stopped

    command: |-
      sh -c 'exec valkey-server --requirepass "$${REDIS_HOST_PASSWORD}"'

    security_opt:
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    networks:
    - default
    volumes:
    - ./data/valkey/data:/data:rw

    env_file:
    - env/valkey
    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: '[ $$(valkey-cli --pass "$${REDIS_HOST_PASSWORD}" ping) = ''PONG'' ]'
      interval: 5s
      start_period: 10s

  fulltextsearch:
    hostname: fulltextsearch
    image: nextcloud/aio-fulltextsearch:${NEXTCLOUD_AIO_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    # FIXME: Investigate why this fails to start with ${GROUP_ID:?}.
    #        Nextcloud AIO seems to be using GID 0 as well:
    #        https://github.com/nextcloud/all-in-one/blob/main/Containers/fulltextsearch/Dockerfile#L21
    user: ${USER_ID:?}:0

    networks:
    - default
    volumes:
    - ./data/fulltextsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data:rw

    environment:
      ES_JAVA_OPTS: "-Xms512M -Xmx512M"
      bootstrap.memory_lock: true
      cluster.name: nextcloud-aio
      discovery.type: single-node
      logger.org.elasticsearch.discovery: WARN
      http.port: 9200
      xpack.license.self_generated.type: basic
      xpack.security.enabled: false
      TZ: ${TZ:?}

    healthcheck:
      test: "curl -f http://localhost:9200 || exit 1"
      interval: 10s
      timeout: 3s
      start_period: 30s

  imaginary:
    hostname: imaginary
    image: nextcloud/aio-imaginary:${NEXTCLOUD_AIO_VERSION:?}
    restart: unless-stopped

    command: -cpus 4 -concurrency 16 -enable-url-source

    cap_add:
    - SYS_NICE
    security_opt:
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    networks:
    - default

    environment:
      PORT: 9000
      TZ: ${TZ:?}

    healthcheck:
      test: "pgrep imaginary"
      interval: 15s
      timeout: 3s
      start_period: 5s

  nextcloud:
    hostname: nextcloud
    image: padhihomelab/nextcloud:${NEXTCLOUD_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    depends_on:
      mariadb:
        condition: service_healthy
      valkey:
        condition: service_healthy
      fulltextsearch:
        condition: service_healthy
      imaginary:
        condition: service_healthy

    networks:
    - default
    - traefik-net
    volumes:
    - ./config/nextcloud/cron.sh:/cron.sh:ro
    - ./data/nextcloud/data:/data:rw
    - ./data/nextcloud/var/www/html:/var/www/html:rw
    # NOTE: Expose `crontabs` to allow for adding or removing cron jobs
    - ./data/nextcloud/crontabs:/crontabs:rw
    # FIXME: See https://github.com/nextcloud/docker/issues/763#issuecomment-1007447212
    - ./data/nextcloud/usr/local/etc/php/conf.d/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:rw
    # FIXME: See https://github.com/nextcloud/docker/issues/1494#issuecomment-1213540687
    - ./data/nextcloud/etc/apache2/conf-enabled/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf:ro

    env_file:
    - env/mariadb
    - env/valkey
    - env/nextcloud
    environment:
      TZ: ${TZ:?}
      # NOTE: Overwrites necessary for reverse proxy
      OVERWRITEPROTOCOL: 'https'
      OVERWRITEWEBROOT: '/${NEXTCLOUD_BASE_PATH:?}'
      NEXTCLOUD_TRUSTED_DOMAINS: ${SERVER_WAN_FQDN:?} ${SERVER_LAN_FQDN:?} nextcloud

    healthcheck:
      test: "curl -fso /dev/null http://localhost:80"
      interval: 15s
      timeout: 3s
      start_period: 15s

  cron:
    hostname: cron
    image: padhihomelab/nextcloud:${NEXTCLOUD_VERSION:?}
    restart: unless-stopped
    entrypoint: /cron.sh

    security_opt:
    - no-new-privileges:true
    # FIXME: `crond` needs to run as `root` user.
    # user: "${USER_ID:?}:${GROUP_ID}"

    depends_on:
      nextcloud:
        condition: service_healthy

    networks:
    - default
    volumes_from:
    - nextcloud:rw

    env_file:
    - env/mariadb
    - env/valkey
    - env/nextcloud
    environment:
      TZ: ${TZ:?}
      # FIXME: See note in config/nextcloud/cron.sh
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}

    healthcheck:
      test: "pgrep -a busybox | grep crond"
      interval: 15s
      timeout: 3s
      start_period: 5s
