version: '2.4'

services:
  nextcloud:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.middlewares.strip-nextcloud-prefix.stripPrefix.prefixes: "/nextcloud"
      traefik.http.routers.nextcloud.rule: PathPrefix(`/nextcloud`)
      traefik.http.routers.nextcloud.entryPoints: wan-https
      traefik.http.routers.nextcloud.middlewares: strip-nextcloud-prefix
