version: '2.4'

networks:
  shared:
    external: true
  proxy:
    external: true

services:
  redis:
    hostname: redis
    image: redis:7.0.4
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    command: |-
      sh -c 'exec redis-server --requirepass "$${REDIS_HOST_PASSWORD}"'

    networks:
    - default
    volumes:
    - ./data/redis/data:/data:rw

    env_file:
    - env/redis
    environment:
      TZ: ${TZ:?}      

    healthcheck:
      test: "redis-cli ping"
      interval: 15s
      start_period: 10s
    logging:
      options:
        max-size: "2m"
        max-file: "1"

  nextcloud:
    hostname: nextcloud
    image: nextcloud:24.0.4
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    depends_on:
    - redis

    networks:
    - default
    - shared
    - proxy
    volumes:
    - ./data/nextcloud/data:/data:rw
    - ./data/nextcloud/var/www/html:/var/www/html:rw
    # FIXME: See https://github.com/nextcloud/docker/issues/763#issuecomment-1007447212
    - ./data/nextcloud/usr/local/etc/php/conf.d/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:rw
    # FIXME: See https://github.com/nextcloud/docker/issues/1494#issuecomment-1213540687
    - ./data/nextcloud/etc/apache2/conf-enabled/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf:ro

    env_file:
    - ../mariadb/env/profiles/nextcloud
    - env/redis
    - env/nextcloud
    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: "curl -fso /dev/null http://localhost:80"
      interval: 15s
      timeout: 3s
      start_period: 15s
    logging:
      options:
        max-size: "16m"
        max-file: "4"

  cron:
    hostname: cron
    image: nextcloud:24.0.4
    restart: unless-stopped
    entrypoint: /cron.sh

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    depends_on:
    - redis
    - nextcloud

    networks:
    - default
    - shared
    volumes_from:
    - nextcloud:rw

    env_file:
    - ../mariadb/env/profiles/nextcloud
    - env/redis
    - env/nextcloud
    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: "pgrep -a busybox | grep crond"
      interval: 15s
      timeout: 3s
      start_period: 5s
    logging:
      options:
        max-size: "4m"
        max-file: "2"
