services:
  uptime:
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.${UPTIME_TRAEFIK_NAMESPACE:?}.loadBalancer.server.port=3001"
    #
    # FIXME: Serve over a basepath
    #
    - "traefik.http.routers.${UPTIME_TRAEFIK_NAMESPACE:?}.rule=Host(`${SERVER_LAN_FQDN:?}`)"
    - "traefik.http.routers.${UPTIME_TRAEFIK_NAMESPACE:?}.entryPoints=lan-https-monitor-exclusive"
