networks:
  traefik-net:
    external: true

services:
  uptime:
    hostname: uptime
    image: louislam/uptime-kuma:${UPTIME_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true

    networks:
    - traefik-net
    volumes:
    - ./data/uptime/app/data:/app/data:rw

    environment:
      PUID: ${USER_ID:?}
      PGID: ${GROUP_ID:?}
      TZ: ${TZ:?}
