services:
  uptime:
    labels:
      traefik.enable: true
      #
      # FIXME: Serve over a basepath
      #
      traefik.http.routers.uptime-lan.rule: Host(`${SERVER_LAN_FQDN:?}`)
      traefik.http.routers.uptime-lan.entryPoints: lan-https-monitor-exclusive
