messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} dashboard may now be accessed on
      ${_LINK_FONT_}https://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTPS_MONITOR_PORT_EXCLUSIVE}${_RESET_FONT_}
    - >-
      ${_THIS_COMPOSITION_} public status pages may now be accessed on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_MONITOR_PORT}/${UPTIME_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
