persistence true
persistence_location /mosquitto/data/

listener 1884 127.0.0.1
listener_allow_anonymous true

listener 1883
listener_allow_anonymous false

plugin /usr/lib/mosquitto_acl_file.so
plugin_opt_acl_file /mosquitto/security/acl

plugin /usr/lib/mosquitto_password_file.so
plugin_opt_password_file /mosquitto/security/passwd
