per_listener_settings true

persistence true
persistence_location /mosquitto/data/

listener 1884 127.0.0.1
allow_anonymous true

listener 1883
allow_anonymous false
acl_file /mosquitto/security/acl
password_file /mosquitto/security/passwd
