services:
  postgres:
    image: postgres:${POSTGRES_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID}"

    network_mode: container:vpn
    volumes:
    - ./data/postgres/var/lib/postgresql/data:/var/lib/postgresql/data:rw

    env_file:
    - env/postgres
    environment:
      PGPORT: 55432

    healthcheck:
      test: "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1'"
      interval: 15s
      timeout: 3s
      start_period: 30s

  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:${BITMAGNET_VERSION:?}
    restart: unless-stopped

    command: worker run --all

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    # FIXME: Run as non-root user

    depends_on:
      postgres:
        condition: service_healthy

    network_mode: container:vpn
    
    env_file:
    - env/postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 55432
      TMDB_ENABLED: false
      DHT_SERVER_PORT: 44444
      HTTP_SERVER_CORS_ALLOWED_ORIGINS: "${SERVER_LAN_FQDN:?}"

    healthcheck:
      test: ["CMD", "curl", "-o", "/dev/null", "-sS", "http://localhost:3333/status"]
      interval: 15s
      start_period: 30s
