messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} may now be accessed on
      ${_LINK_FONT_}https://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTPS_PORT_A}/${_RESET_FONT_}

pre_req:
- openvpn

related:
- traefik
