networks:
  traefik-net:
    external: true

services:
  lidarr:
    hostname: lidarr
    image: padhihomelab/lidarr:${LIDARR_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - traefik-net
    volumes:
    - ./data/lidarr/config:/config:rw
    - ./data/lidarr/downloads:/downloads:rw
    - ./data/lidarr/music:/music:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}

  radarr:
    hostname: radarr
    image: padhihomelab/radarr:${RADARR_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - traefik-net
    volumes:
    - ./data/radarr/config:/config:rw
    - ./data/radarr/downloads:/downloads:rw
    - ./data/radarr/movies:/movies:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}

  sonarr:
    hostname: sonarr
    image: padhihomelab/sonarr:${SONARR_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - traefik-net
    volumes:
    - ./data/sonarr/config:/config:rw
    - ./data/sonarr/downloads:/downloads:rw
    - ./data/sonarr/tv:/tv:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}
