version: '2.4'

networks:
  proxy:
    external: true

services:
  lidarr:
    hostname: lidarr
    image: padhihomelab/lidarr:1.1.0.2602
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/lidarr/config:/config:rw
    - ./data/lidarr/downloads:/downloads:rw
    - ./data/lidarr/music:/music:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.lidarr.rule: PathPrefix(`/lidarr`)
      traefik.http.routers.lidarr.entryPoints: wan-https

  radarr:
    hostname: radarr
    image: padhihomelab/radarr:4.2.1.6478
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/radarr/config:/config:rw
    - ./data/radarr/downloads:/downloads:rw
    - ./data/radarr/movies:/movies:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.radarr.rule: PathPrefix(`/radarr`)
      traefik.http.routers.radarr.entryPoints: wan-https

  sonarr:
    hostname: sonarr
    image: padhihomelab/sonarr:3.0.9.1549
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/sonarr/config:/config:rw
    - ./data/sonarr/downloads:/downloads:rw
    - ./data/sonarr/tv:/tv:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.sonarr.rule: PathPrefix(`/sonarr`)
      traefik.http.routers.sonarr.entryPoints: wan-https
