version: '2.4'

services:
  lidarr:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.lidarr.rule: PathPrefix(`/lidarr`)
      traefik.http.routers.lidarr.entryPoints: wan-https
  radarr:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.radarr.rule: PathPrefix(`/radarr`)
      traefik.http.routers.radarr.entryPoints: wan-https
  sonarr:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.sonarr.rule: PathPrefix(`/sonarr`)
      traefik.http.routers.sonarr.entryPoints: wan-https
