networks:
  proxy:
    external: true

services:
  lidarr:
    hostname: lidarr
    image: padhihomelab/lidarr:2.8.2.4493
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/lidarr/config:/config:rw
    - ./data/lidarr/downloads:/downloads:rw
    - ./data/lidarr/music:/music:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}

  radarr:
    hostname: radarr
    image: padhihomelab/radarr:5.17.2.9580
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/radarr/config:/config:rw
    - ./data/radarr/downloads:/downloads:rw
    - ./data/radarr/movies:/movies:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}

  sonarr:
    hostname: sonarr
    image: padhihomelab/sonarr:4.0.12.2823
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/sonarr/config:/config:rw
    - ./data/sonarr/downloads:/downloads:rw
    - ./data/sonarr/tv:/tv:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}
