version: '2.4'

networks:
  proxy:
    external: true

services:
  lidarr:
    hostname: lidarr
    image: padhihomelab/lidarr:1.2.1.3216
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/lidarr/config:/config:rw
    - ./data/lidarr/downloads:/downloads:rw
    - ./data/lidarr/music:/music:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

  radarr:
    hostname: radarr
    image: padhihomelab/radarr:4.5.2.7318
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/radarr/config:/config:rw
    - ./data/radarr/downloads:/downloads:rw
    - ./data/radarr/movies:/movies:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}

  sonarr:
    hostname: sonarr
    image: padhihomelab/sonarr:3.0.10.1567
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/sonarr/config:/config:rw
    - ./data/sonarr/downloads:/downloads:rw
    - ./data/sonarr/tv:/tv:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
