messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_}:lidarr may now be accessed on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_SERVICE_PORT}/${LIDARR_BASE_PATH}/${_RESET_FONT_}
    - >-
      ${_THIS_COMPOSITION_}:radarr may now be accessed on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_SERVICE_PORT}/${RADARR_BASE_PATH}/${_RESET_FONT_}
    - >-
      ${_THIS_COMPOSITION_}:sonarr may now be accessed on
      ${_LINK_FONT_}https://${SERVER_WAN_FQDN}:${SERVER_WAN_HTTPS_SERVICE_PORT}/${SONARR_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
