services:
  beszel:
    labels:
      traefik.enable: true
      #
      traefik.http.middlewares.strip-beszel-prefix.stripPrefix.prefixes: "/${BESZEL_HUB_BASE_PATH:?}"
      #
      traefik.http.routers.beszel.rule: Host(`${SERVER_LAN_FQDN:?}`) && PathPrefix(`/${BESZEL_HUB_BASE_PATH:?}`)
      traefik.http.routers.beszel.entryPoints: lan-https-monitor
      traefik.http.routers.beszel.middlewares: strip-beszel-prefix
