networks:
  beszel:
    external: true
  traefik-net:
    external: true

services:
  beszel:
    hostname: beszel
    image: henrygd/beszel:${BESZEL_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true
    user: "${USER_ID:?}:${GROUP_ID:?}"

    networks:
    - beszel
    - traefik-net
    volumes:
    - ./data/beszel/beszel_data:/beszel_data:rw

    environment:
      BESZEL_HUB_USER_CREATION: false
      BESZEL_HUB_APP_URL: "https://${SERVER_LAN_FQDN:?}:${SERVER_LAN_HTTPS_MONITOR_PORT:?}/${BESZEL_HUB_BASE_PATH:?}"

    healthcheck:
      test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
      start_period: 30s
      interval: 5s
      timeout: 2s
