messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} is now listening on
      ${_LINK_FONT_}http://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTPS_MONITOR_PORT}/${BESZEL_HUB_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
