networks:
  traefik-net:
    external: true

services:
  mariadb:
    hostname: mariadb
    image: mariadb:${MARIADB_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true
    user: "${USER_ID:?}:${GROUP_ID:?}"

    networks:
    - default
    volumes:
    - ./data/mariadb/var/lib/mysql:/var/lib/mysql:rw

    environment:
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE:?}
      MYSQL_USER: ${MYSQL_USER:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}

    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 15s
      start_period: 30s

  hortusfox:
    hostname: hortusfox
    image: ghcr.io/danielbrendel/hortusfox-web:${HORTUSFOX_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges=true
    user: "${USER_ID:?}:${GROUP_ID:?}"

    depends_on:
      mariadb:
        condition: service_healthy

    networks:
    - default
    - traefik-net
    volumes:
    - ./data/hortusfox/var/www/html/app/logs:/var/www/html/app/logs:rw
    - ./data/hortusfox/var/www/html/app/migrations:/var/www/html/app/migrations:rw
    - ./data/hortusfox/var/www/html/public/backup:/var/www/html/public/backup:rw
    - ./data/hortusfox/var/www/html/public/img:/var/www/html/public/img:rw
    - ./data/hortusfox/var/www/html/public/themes:/var/www/html/public/themes:rw

    environment:
      APP_ADMIN_EMAIL: admin@some.doma.in
      APP_ADMIN_PASSWORD: "5p3r.53cur3#p455w0rd"
      APP_TIMEZONE: ${TZ:?}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:?}
      DB_USERNAME: ${MYSQL_USER:?}
      DB_PASSWORD: ${MYSQL_PASSWORD:?}
      DB_CHARSET: "utf8mb4"
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "curl", "-fso", "/dev/null", "http://localhost/"]
      interval: 15s
      timeout: 2s
      start_period: 5s
