version: '2.4'

networks:
  shared:
    external: true

services:
  mariadb:
    hostname: mariadb
    image: mariadb:10.8.3
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}
    
    command: |-
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --innodb-file-per-table=1
      --skip-innodb-read-only-compressed

    networks:
    - shared
    volumes:
    - ./config/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    - ./config/mariadb/healthcheck.sh:/healthcheck.sh:ro
    - ./data/mariadb/var/lib/mysql:/var/lib/mysql:rw
    - ./env/profiles:/profiles:ro

    env_file:
    - env/mariadb
    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 15s
      start_period: 10s
    logging:
      options:
        max-size: "2m"
        max-file: "1"
