networks:
  beszel:
    external: true
  docker-sock:
    external: true

services:
  agent:
    hostname: ${HOST_NAME:?}
    container_name: beszel-agent
    image: henrygd/beszel-agent:${BESZEL_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - beszel
    - docker-sock

    environment:
      BESZEL_AGENT_DOCKER_HOST: "tcp://docker.sock-proxy:1279"
      BESZEL_AGENT_KEY: "paste_ssh_key_from_hub"
      BESZEL_AGENT_LISTEN: ${BESZEL_AGENT_PORT:?}

    healthcheck:
      test: ['CMD', '/agent', 'health']
      start_period: 5s
      interval: 120s
