version: '2.4'

services:
  netdata:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.middlewares.strip-netdata-prefix.stripprefix.prefixes: "/netdata"
      traefik.http.routers.netdata.rule: PathPrefix(`/netdata`)
      traefik.http.routers.netdata.entryPoints: local-secure
      traefik.http.routers.netdata.middlewares: strip-netdata-prefix
