accessLog:
  format: json
  filters:
    statusCodes:
    - "400-499"
    - "500-599"
    minDuration: "5s"
  fields:
    defaultMode: drop
    names:
      Duration: keep
      RouterName: keep
      ServiceName: keep
      ClientAddr: keep
      RequestAddr: keep
      RequestPath: keep
      RequestProtocol: keep
      RequestScheme: keep
      RequestContentSize: keep
      OriginStatus: keep
      DownstreamStatus: keep
      Overhead: keep
      RetryAttempts: keep
      TLSVersion: keep
    headers:
      defaultMode: drop
      names:
        Referer: keep
        User-Agent: keep

api:
  dashboard: true
  insecure: false

entryPoints:
  internal:
    address: ":8080"
  lan-internal:
    address: ":34443"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-http-a:
    address: ":${SERVER_LAN_HTTP_PORT_A}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
  lan-https-a:
    address: ":${SERVER_LAN_HTTPS_PORT_A}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-http-b:
    address: ":${SERVER_LAN_HTTP_PORT_B}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
  lan-https-b:
    address: ":${SERVER_LAN_HTTPS_PORT_B}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  wan-https:
    address: ":${SERVER_WAN_HTTPS_PORT}"
    http:
      middlewares:
      - block-ddos-attacks@file
      - default@file
      - add-ssl-headers@file
      tls:
        domains:
        - main: ${SERVER_WAN_FQDN}

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  format: json
  level: INFO

ping:
  entryPoint: internal

providers:
  docker:
    endpoint: "tcp://docker.sock-proxy:1279"
    exposedByDefault: false
    network: proxy
    watch: true
  file:
    directory: "/dynamic"
    watch: true

serversTransport:
  insecureSkipVerify: true
