accessLog:
  format: json
  filters:
    statusCodes:
    - "400-499"
    - "500-599"
    minDuration: "5s"
  fields:
    defaultMode: drop
    names:
      Duration: keep
      RouterName: keep
      ServiceName: keep
      ClientAddr: keep
      RequestAddr: keep
      RequestPath: keep
      RequestProtocol: keep
      RequestScheme: keep
      RequestContentSize: keep
      OriginStatus: keep
      DownstreamStatus: keep
      Overhead: keep
      RetryAttempts: keep
      TLSVersion: keep
    headers:
      defaultMode: drop
      names:
        Referer: keep
        User-Agent: keep

api:
  dashboard: true
  insecure: false
  basePath: /${TRAEFIK_UI_BASE_PATH}

entryPoints:
  x-internal:
    address: ":8080"
  lan-http-service:
    address: ":${SERVER_LAN_HTTP_SERVICE_PORT}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
  lan-http-service-exclusive:
    address: ":${SERVER_LAN_HTTP_SERVICE_PORT_EXCLUSIVE}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
  lan-https-internal:
    address: ":${SERVER_LAN_HTTPS_INTERNAL_PORT}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-https-internal-exclusive:
    address: ":${SERVER_LAN_HTTPS_INTERNAL_PORT_EXCLUSIVE}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-https-monitor:
    address: ":${SERVER_LAN_HTTPS_MONITOR_PORT}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-https-monitor-exclusive:
    address: ":${SERVER_LAN_HTTPS_MONITOR_PORT_EXCLUSIVE}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-https-service:
    address: ":${SERVER_LAN_HTTPS_SERVICE_PORT}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  lan-https-service-exclusive:
    address: ":${SERVER_LAN_HTTPS_SERVICE_PORT_EXCLUSIVE}"
    http:
      middlewares:
      - restrict-to-lan-ip@file
      - default@file
      - add-ssl-headers@file
      tls: true
  wan-https-monitor:
    address: ":${SERVER_WAN_HTTPS_MONITOR_PORT}"
    http:
      middlewares:
      - block-ddos-attacks@file
      - default@file
      - add-ssl-headers@file
      tls:
        domains:
        - main: ${SERVER_WAN_FQDN}
  wan-https-monitor-exclusive:
    address: ":${SERVER_WAN_HTTPS_MONITOR_PORT_EXCLUSIVE}"
    http:
      middlewares:
      - block-ddos-attacks@file
      - default@file
      - add-ssl-headers@file
      tls:
        domains:
        - main: ${SERVER_WAN_FQDN}
  wan-https-service:
    address: ":${SERVER_WAN_HTTPS_SERVICE_PORT}"
    http:
      middlewares:
      - block-ddos-attacks@file
      - default@file
      - add-ssl-headers@file
      tls:
        domains:
        - main: ${SERVER_WAN_FQDN}
  wan-https-service-exclusive:
    address: ":${SERVER_WAN_HTTPS_SERVICE_PORT_EXCLUSIVE}"
    http:
      middlewares:
      - block-ddos-attacks@file
      - default@file
      - add-ssl-headers@file
      tls:
        domains:
        - main: ${SERVER_WAN_FQDN}

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  format: json
  level: INFO

ping:
  entryPoint: x-internal

providers:
  docker:
    endpoint: "tcp://docker.sock-proxy:1279"
    exposedByDefault: false
    network: traefik-net
    watch: true
  file:
    directory: "/dynamic"
    watch: true

serversTransport:
  insecureSkipVerify: true
