services:
  mongo:
    hostname: mongo
    image: mongo:${MONGO_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: "${USER_ID:?}:${GROUP_ID:?}"

    volumes:
    - ./data/mongo/data/db:/data/db:rw

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok", "localhost:27017/test", "--quiet"]
      interval: 15s
      timeout: 5s
      start_period: 5s

  unifi:
    hostname: unifi
    image: goofball222/unifi:${UNIFI_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    depends_on:
      mongo:
        condition: service_healthy

    volumes:
    - ./data/unifi/usr/lib/unifi/cert:/usr/lib/unifi/cert:rw
    - ./data/unifi/usr/lib/unifi/data:/usr/lib/unifi/data:rw
    - ./data/unifi/usr/lib/unifi/logs:/usr/lib/unifi/logs:rw

    environment:
      DB_MONGO_LOCAL: 'false'
      DB_MONGO_URI: mongodb://mongo/unifi
      PUID: ${USER_ID:?}
      PGID: ${GROUP_ID:?}
      STATDB_MONGO_URI: mongodb://mongo/unifi_stat
      UNIFI_DB_NAME: unifi
      TZ: ${TZ:?}
