version: '2.4'

services:
  mongo:
    hostname: mongo
    # MongoDB 5.0+ requires ARMv8.2A+
    image: mongo:4.4.17
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    volumes:
    - ./data/mongo/data/db:/data/db:rw

    environment:
      PUID: ${USER_ID:?}
      PGID: ${GROUP_ID:?}
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok", "localhost:27017/test", "--quiet"]
      interval: 15s
      timeout: 5s
      start_period: 5s
    logging:
      options:
        max-size: "2m"
        max-file: "1"

  unifi:
    hostname: unifi
    image: goofball222/unifi:7.2.94-alpine
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    depends_on:
    - mongo

    volumes:
    - ./data/unifi/usr/lib/unifi/cert:/usr/lib/unifi/cert:rw
    - ./data/unifi/usr/lib/unifi/data:/usr/lib/unifi/data:rw
    - ./data/unifi/usr/lib/unifi/logs:/usr/lib/unifi/logs:rw

    environment:
      DB_MONGO_LOCAL: 'false'
      DB_MONGO_URI: mongodb://mongo/unifi
      PUID: ${USER_ID:?}
      PGID: ${GROUP_ID:?}
      STATDB_MONGO_URI: mongodb://mongo/unifi_stat
      UNIFI_DB_NAME: unifi
      TZ: ${TZ:?}

    logging:
      options:
        max-size: "8m"
        max-file: "4"
