version: '2.4'

services:
  docker.sock-proxy:
    labels:
      traefik.enable: true
      traefik.docker.network: shared
      traefik.http.routers.docker_sock.rule: PathPrefix(`/docker.sock`)
      traefik.http.services.docker_sock.loadBalancer.server.port: 9000
      traefik.http.routers.docker_sock.entryPoints: lan-https
