version: '2.4'

networks:
  shared:
    external: true

services:
  docker.sock-proxy:
    hostname: docker.sock-proxy
    image: padhihomelab/docker.sock-proxy:2.8.10
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - shared
    volumes:
    - ./data/docker.sock-proxy/haproxy:/haproxy:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      # For querying labels etc.
      CONTAINERS: '1'
      # For Traefik network events
      EVENTS: '1'
      # For Telegraf monitoring
      INFO: '1'
      TZ: ${TZ:?}
