networks:
  proxy:
    external: true

services:
  http:
    hostname: http
    image: padhihomelab/tiny-httpd:${TINY_HTTPD_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/http/www:/www:ro

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
      TZ: ${TZ:?}
