services:
  http:
    labels:
      traefik.enable: true
      #
      # NOTE: This is not an "exclusive" port use.
      #       It is intended to serve as a catch-all case for unmatched paths.
      #
      traefik.http.routers.http.rule: Host(`${SERVER_WAN_FQDN:?}`)
      traefik.http.routers.http.entryPoints: wan-https-svc
