services:
  airdcpp:
    image: padhihomelab/airdcpp:${AIRDCPP_VERSION:?}
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    network_mode: container:vpn
    volumes:
    - ./config/airdcpp/etc/docker-entrypoint.d/99-user-scripts:/etc/docker-entrypoint.d/99-user-scripts:ro
    - ./data/airdcpp/config:/config:rw
    - ./data/airdcpp/downloads:/downloads:rw
    - ./data/airdcpp/shared:/shared:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
