services:
  airdcpp:
    labels:
    - "traefik.enable=true"
    - "traefik.http.services.${AIRDCPP_TRAEFIK_NAMESPACE:?}.loadBalancer.server.port=5600"
    #
    - "traefik.http.middlewares.strip-prefix-for-${AIRDCPP_TRAEFIK_NAMESPACE:?}.stripPrefix.prefixes=/${AIRDCPP_BASE_PATH:?}"
    #
    - "traefik.http.routers.${AIRDCPP_TRAEFIK_NAMESPACE:?}.rule=Host(`${SERVER_WAN_FQDN:?}`) && PathPrefix(`/${AIRDCPP_BASE_PATH:?}`)"
    - "traefik.http.routers.${AIRDCPP_TRAEFIK_NAMESPACE:?}.entryPoints=wan-https-service"
    - "traefik.http.routers.${AIRDCPP_TRAEFIK_NAMESPACE:?}.middlewares=strip-prefix-for-${AIRDCPP_TRAEFIK_NAMESPACE:?}"
