version: '2.4'

networks:
  default:

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.5.2

    networks:
    - default
    volumes:
    - ./data/openvpn/config:/config:ro

    cap_add:
    - NET_ADMIN

    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'
      TZ: ${TZ:?}

  airdcpp:
    image: padhihomelab/airdcpp:2.11.2
    restart: unless-stopped

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
    - ./data/airdcpp/config:/config:rw
    - ./data/airdcpp/downloads:/downloads:rw
    - ./data/airdcpp/shared:/shared:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
