version: '2.4'

networks:
  default:

services:
  caddy:
    hostname: caddy
    image: caddy:2.4.5
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - airdcpp
    links:
    - openvpn:airdcpp
  
    networks:
    - default
    volumes:
    - ./config/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    healthcheck:
      test: ["CMD", "wget", "-qSO", "/dev/null", "http://localhost:2019/config"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.5.2

    networks:
    - default
    volumes:
    - ./data/openvpn/config:/config:ro

    cap_add:
    - NET_ADMIN
    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'

  airdcpp:
    image: padhihomelab/airdcpp:2.11.2
    restart: unless-stopped

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
    - ./data/airdcpp/config:/config:rw
    - ./data/airdcpp/downloads:/downloads:rw
    - ./data/airdcpp/shared:/shared:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
