version: '2.4'

networks:
  proxy:
    external: true

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.5.6
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/openvpn/config:/config:ro

    cap_add:
    - NET_ADMIN
    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'

  airdcpp:
    image: padhihomelab/airdcpp:2.11.2
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
    - ./config/airdcpp/etc/docker-entrypoint.d/99-user-scripts:/etc/docker-entrypoint.d/99-user-scripts:ro
    - ./data/airdcpp/config:/config:rw
    - ./data/airdcpp/downloads:/downloads:rw
    - ./data/airdcpp/shared:/shared:rw

    environment:
      DOCKER_UID: ${USER_ID:?}

    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.middlewares.strip-airdcpp-prefix.stripPrefix.prefixes: "/airdcpp"
      traefik.http.routers.airdcpp.rule: PathPrefix(`/airdcpp`)
      traefik.http.services.airdcpp.loadBalancer.server.port: 5600
      traefik.http.routers.airdcpp.entryPoints: wan-https
      traefik.http.routers.airdcpp.middlewares: strip-airdcpp-prefix
      
