networks:
  proxy:
    external: true

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:${OPENVPN_CLIENT_VERSION:?}
    restart: unless-stopped

    cap_add:
    - NET_ADMIN
    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/openvpn/config:/config:ro

    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'

  airdcpp:
    image: padhihomelab/airdcpp:${AIRDCPP_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    depends_on:
      openvpn:
        condition: service_healthy

    network_mode: service:openvpn
    volumes:
    - ./config/airdcpp/etc/docker-entrypoint.d/99-user-scripts:/etc/docker-entrypoint.d/99-user-scripts:ro
    - ./data/airdcpp/config:/config:rw
    - ./data/airdcpp/downloads:/downloads:rw
    - ./data/airdcpp/shared:/shared:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
