version: '2.4'

networks:
  proxy:
    external: true

services:
  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.6.4
    restart: unless-stopped

    cap_add:
    - NET_ADMIN
    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/openvpn/config:/config:ro

    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      PROXY_USERNAME: 'user'
      PROXY_PASSWORD: 'pass'

  airdcpp:
    image: padhihomelab/airdcpp:2.12.1
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
    - ./config/airdcpp/etc/docker-entrypoint.d/99-user-scripts:/etc/docker-entrypoint.d/99-user-scripts:ro
    - ./data/airdcpp/config:/config:rw
    - ./data/airdcpp/downloads:/downloads:rw
    - ./data/airdcpp/shared:/shared:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
