version: '2.4'

networks:
  proxy:
    external: true

services:
  influxdb:
    hostname: influxdb
    image: influxdb:2.5.1-alpine
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    networks:
    - default
    volumes:
    - ./data/influxdb/etc/influxdb2:/etc/influxdb2
    - ./data/influxdb/var/lib/influxdb2:/var/lib/influxdb2

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin_password
      DOCKER_INFLUXDB_INIT_ORG: default
      DOCKER_INFLUXDB_INIT_BUCKET: default
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin_token
      INFLUXD_FLUX_LOG_ENABLED: 'true'
      INFLUXD_REPORTING_DISABLED: 'true'
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user_password
      INFLUXDB_READ_USER: reader
      INFLUXDB_READ_USER_PASSWORD: reader_password

  telegraf:
    hostname: telegraf
    image: telegraf:1.24.3
    restart: unless-stopped
    command: telegraf --config-directory /etc/telegraf/telegraf.conf.d

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    depends_on:
    - influxdb

    networks:
    - default
    volumes:
    - ./config/telegraf/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

    environment:
      HOST_NAME: ${HOST_NAME:?}
      SERVER_LAN_FQDN: ${SERVER_LAN_FQDN:?}
      SERVER_LAN_HTTPS_PORT: ${SERVER_LAN_HTTPS_PORT:?}
      TELEGRAF_LOGGING_FILE: STDOUT
      TELEGRAF_REPORTING_ENABLED: 'false'

  kapacitor:
    hostname: kapacitor
    image: kapacitor:1.6.5
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    depends_on:
    - influxdb

    networks:
    - default
    volumes:
    - ./data/kapacitor/.kapacitor:/.kapacitor
    - ./data/kapacitor/etc/kapacitor:/etc/kapacitor
    - ./data/kapacitor/var/lib/kapacitor:/var/lib/kapacitor

    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_HTTP_LOG_ENABLED: 'false'
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      KAPACITOR_INFLUXDB_0_DISABLE_SUBSCRIPTIONS: 'true'
      KAPACITOR_LOGGING_FILE: STDOUT
      KAPACITOR_REPORTING_ENABLED: 'false'
      TZ: ${TZ:?}

  chronograf:
    hostname: chronograf
    # FIXME: Use `nightly` image until the fix for
    # https://github.com/influxdata/chronograf/issues/6008
    # is pushed to a stable image.
    image: quay.io/influxdb/chronograf:nightly
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    depends_on:
    - influxdb
    - kapacitor
    - telegraf

    networks:
    - default
    - proxy
    volumes:
    - ./data/chronograf/var/lib/chronograf:/var/lib/chronograf

    environment:
      BASE_PATH: "/tick"
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: default
      INFLUXDB_TOKEN: admin_token
      KAPACITOR_URL: http://kapacitor:9092
      REPORTING_DISABLED: 'true'
