http:
  middlewares:
    add-ssl-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: 'https,wss'
        forceSTSHeader: true
        isDevelopment: false
        stsIncludeSubdomains: false
        stsPreload: true
        stsSeconds: 31536000

    restrict-to-lan-ip:
      ipAllowList:
        sourceRange:
        - '10.0.0.0/8'
        - '127.0.0.1/8'
        - '172.16.0.0/12'
        - '192.168.0.0/16'

    default:
      chain:
        middlewares:
        - add-security-headers
        - compress-response
    add-security-headers:
      headers:
        browserXSSFilter: true
        contentTypeNoSniff: true
        customResponseHeaders:
          Permissions-Policy: 'geolocation=(self), microphone=(), camera=(), fullscreen=*'
          Server: ''
          X-Powered-By: ''
          X-Robots-Tag: 'none,noarchive,nofollow,noimageindex,noindex,nosnippet,notranslate'
        customFrameOptionsValue: 'sameorigin'
        permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        referrerPolicy: 'same-origin'
    compress-response:
      compress:
        excludedContentTypes:
        - 'text/event-stream'

    block-ddos-attacks:
      chain:
        middlewares:
        - limit-in-flight-requests
        - limit-rate
    limit-in-flight-requests:
      inFlightReq:
        amount: 128
    limit-rate:
      rateLimit:
        average: 64
        burst: 32
