networks:
  traefik-net:
    external: true

services:
  tang:
    hostname: tang
    image: padhihomelab/tang:${TANG_VERSION:?}
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true

    networks:
    - traefik-net
    volumes:
    - ./data/tang/db:/db:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      DOCKER_GID: ${GROUP_ID:?}
