version: '2.4'

services:
  tang:
    hostname: tang
    image: padhihomelab/tang:git.e2059ee1_git.76924deb
    restart: unless-stopped

    volumes:
    - ./data/tang/db:/db:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
