version: '2.4'

networks:
  proxy:
    external: true

services:
  tang:
    hostname: tang
    image: padhihomelab/tang:git.7c0d86f5_git.e1d66f13
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/tang/db:/db:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
