version: '2.4'

services:
  tang:
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.middlewares.strip-tang-prefix.stripprefix.prefixes: "/tang"
      traefik.http.routers.tang.rule: PathPrefix(`/tang`)
      traefik.http.routers.tang.entryPoints: local
      traefik.http.routers.tang.middlewares: strip-tang-prefix
