version: '2.4'

networks:
  proxy:
    external: true

services:
  tang:
    hostname: tang
    image: padhihomelab/tang:git.3d6efb10_git.3d5b2872
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true

    networks:
    - proxy
    volumes:
    - ./data/tang/db:/db:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
