services:
  tang:
    labels:
      traefik.enable: true
      traefik.http.middlewares.strip-tang-prefix.stripPrefix.prefixes: "/${TANG_BASE_PATH:?}"
      traefik.http.routers.tang.rule: PathPrefix(`/${TANG_BASE_PATH:?}`)
      traefik.http.routers.tang.entryPoints: lan-http
      traefik.http.routers.tang.middlewares: strip-tang-prefix
