messages:
  up:
    post:
    - >-
      ${_THIS_COMPOSITION_} is now listening on
      ${_LINK_FONT_}http://${SERVER_LAN_FQDN}:${SERVER_LAN_HTTP_SERVICE_PORT}/${TANG_BASE_PATH}/${_RESET_FONT_}

related:
- traefik
