networks:
  shared:
    external: true

services:
  telegraf:
    hostname: telegraf
    image: telegraf:1.33.0
    restart: unless-stopped

    security_opt:
    # NOTE: Do NOT add a [space] before `true` below.
    - no-new-privileges:true
    user: ${USER_ID:?}

    networks:
    - shared
    volumes:
    - ./config/telegraf/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - ./config/telegraf/etc/telegraf/scripts:/etc/telegraf/scripts:ro
    - ./config/telegraf/etc/telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro

    environment:
      HOST_NAME: ${HOST_NAME:?}
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_MOUNT_PREFIX: /host
      TELEGRAF_LOGGING_FILE: STDOUT
      TELEGRAF_REPORTING_ENABLED: 'false'
      INFLUXDB_URL: http://${SERVER_LAN_FQDN:?}:8086
      INFLUXDB_ORG: default
      INFLUXDB_BUCKET: default
      INFLUXDB_ADMIN_TOKEN: 'admin_token'

    healthcheck:
      test: ["CMD", "curl", "-o", "/dev/null", "-sS", "http://localhost:8080/"]
      interval: 15s
      timeout: 2s
      start_period: 5s
