version: '2.4'

services:
  influxdb:
    hostname: influxdb
    image: influxdb:2.5.1-alpine
    restart: unless-stopped

    security_opt:
    - no-new-privileges:true
    user: ${USER_ID:?}

    volumes:
    - ./data/influxdb/certs:/certs
    - ./data/influxdb/etc/influxdb2:/etc/influxdb2
    - ./data/influxdb/var/lib/influxdb2:/var/lib/influxdb2

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin_password
      DOCKER_INFLUXDB_INIT_ORG: default
      DOCKER_INFLUXDB_INIT_BUCKET: default
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin_token
      INFLUXD_FLUX_LOG_ENABLED: 'true'
      INFLUXD_REPORTING_DISABLED: 'true'
      INFLUXD_TLS_CERT: /cert/default.crt
      INFLUXD_TLS_KEY: /cert/default.key

    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 15s
      timeout: 2s
      start_period: 5s
    logging:
      options:
        max-size: "8m"
        max-file: "4"
