name: "Docker Compose Test (Monitarr)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

env:
  TARGET_SERVICE: monitarr
  TARGET_TIMEOUT: 60

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v4
      -
        name: "Service: Setup"
        run: |
          cp .github/workflows/config/options.conf "${TARGET_SERVICE}/options.override.conf"
          cp .github/workflows/config/options.conf "traefik/options.override.conf"
      -
        name: "Service: Start"
        run: |
          ./compositions.sh up --labels NEVER ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          cd ${TARGET_SERVICE} ; cat .env
          sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test"
        run: |
          if ! ./compositions.sh check ${TARGET_SERVICE}; then
            docker ps
            cd ${TARGET_SERVICE} ; docker-compose logs
            exit 1
          fi
      -
        name: "Service: Restart with Traefik"
        run: |
          ./compositions.sh up traefik
          ./compositions.sh down,up ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          sleep ${TARGET_TIMEOUT}s ; sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test with Traefik"
        run: |
          if ! ./compositions.sh check ${TARGET_SERVICE} traefik; then
            docker ps
            cd ${TARGET_SERVICE} ; docker-compose logs
            cd traefik ; docker-compose logs
            exit 1
          fi
          cd traefik
          docker-compose exec -T traefik wget --spider --no-check-certificate https://localhost/lidarr/ \
            || (docker ps ; docker-compose logs ; cd ../${TARGET_SERVICE} ; docker-compose logs ; exit 1)
          docker-compose exec -T traefik wget --spider --no-check-certificate https://localhost/radarr/ \
            || (docker ps ; docker-compose logs ; cd ../${TARGET_SERVICE} ; docker-compose logs ; exit 1)
          docker-compose exec -T traefik wget --spider --no-check-certificate https://localhost/sonarr/ \
            || (docker ps ; docker-compose logs ; cd ../${TARGET_SERVICE} ; docker-compose logs ; exit 1)
