name: "Docker Compose Test (Certbot)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

env:
  TARGET_SERVICE: certbot
  TARGET_TIMEOUT: 30

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v4
      -
        name: "Service: Setup"
        run: |
          cp .github/workflows/config/options.conf "${TARGET_SERVICE}/options.override.conf"
      -
        name: "Service: Start"
        run: |
          ./comp up --labels no ${TARGET_SERVICE}
          cd ${TARGET_SERVICE} ; cat .env
