name: "Docker Compose Test (I2P)"

on: workflow_dispatch

env:
  TARGET_SERVICE: i2p
  TARGET_TIMEOUT: 30

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v3
      -
        name: "Service: Start"
        run: |
          ./composition.sh up --no-labels ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test"
        run: |
          if ! ./composition.sh check ${TARGET_SERVICE}; then
            docker ps
            cd ${TARGET_SERVICE} ; docker-compose logs
            exit 1
          fi
