name: "Docker Compose Test (qBittorrent)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v3
      -
        name: "Service: Setup"
        run: |
          mkdir -p airdcpp/data/openvpn
          cp -r .github/workflows/config/vpn airdcpp/data/openvpn/config
      -
        name: "Service: Start"
        run: |
          ./service.sh up --no-override qbittorrent
      -
        name: "Service: Wait"
        run: |
          sleep 45s
      -
        name: "Service: Test"
        run: |
          cd qbittorrent
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q qbittorrent))"
          [[ "$REPLY" == '"healthy"' ]] || (docker ps && docker-compose logs && exit 1)
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q caddy))"
          [[ "$REPLY" == '"healthy"' ]] || (docker ps && docker-compose logs && exit 1)
