name: "Docker Compose Test (MariaDB)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

env:
  TARGET_SERVICE: mariadb
  TARGET_TIMEOUT: 30

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v3
      -
        name: "Service: Start"
        run: |
          ./composition.sh up --no-labels --no-ports ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test"
        run: |
          if ! ./composition.sh check ${TARGET_SERVICE}; then
            docker ps
            cd ${TARGET_SERVICE} ; docker-compose logs
            exit 1
          fi
