name: "Docker Compose Test (netdata)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v3
      -
        name: "Service: Start"
        run: |
          ./service.sh up --no-override netdata
      -
        name: "Service: Wait"
        run: |
          sleep 10s
      -
        name: "Service: Test"
        run: |
          cd netdata
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || (docker ps && docker-compose logs && exit 1)
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q caddy))"
          [[ "$REPLY" == '"healthy"' ]] || (docker ps && docker-compose logs && exit 1)
