name: "Docker Compose Test (AirDC++)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: Setup"
        run: |
          mkdir -p airdcpp/data/openvpn/config
          wget "https://www.vpngate.net/common/openvpn_download.aspx?sid=1609387551919&tcp=1&host=219.100.37.63&port=443&hid=15094317&/vpngate_219.100.37.63_tcp_443.ovpn" \
               -O airdcpp/data/openvpn/config/client.conf
          echo -e "\nauth-user-pass login.txt" >> airdcpp/data/openvpn/config/client.conf
          echo -e "vpn\nvpn" > airdcpp/data/openvpn/config/login.txt
      -
        name: "Service: Start"
        run: |
          ./service.sh up --no-override airdcpp
      -
        name: "Service: Wait"
        run: |
          sleep 15s
      -
        name: "Service: Test"
        run: |
          cd airdcpp
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q airdcpp))"
          [[ "$REPLY" == '"healthy"' ]] || (docker-compose logs && exit 1)
