name: "Docker Compose Test (Kodi_DB)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

env:
  TARGET_SERVICE: kodi_db
  TARGET_TIMEOUT: 60

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-24.04 , ubuntu-24.04-arm ]
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v5
      -
        name: "Service: Setup"
        run: |
          cp .github/workflows/config/meta.override.yml "${TARGET_SERVICE}/"
      -
        name: "Service: Start"
        run: |
          ./comp up --labels ignore ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          cd ${TARGET_SERVICE} ; cat .env
          sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test"
        run: |
          if ! ./comp status ${TARGET_SERVICE}; then
            docker ps
            cd ${TARGET_SERVICE} ; docker compose logs
            exit 1
          fi
