name: "Docker Compose Test (netdata)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

env:
  TARGET_SERVICE: netdata
  TARGET_TIMEOUT: 15

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v3
      -
        name: "Service: Start"
        run: |
          ./composition.sh up --no-labels --no-ports ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test"
        run: |
          if ! ./composition.sh check ${TARGET_SERVICE}; then
            docker ps
            cd ${TARGET_SERVICE} ; docker-compose logs
            exit 1
          fi
          cd netdata
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || (docker ps ; docker-compose logs ; exit 1)
      -
        name: "Service: Traefik Setup"
        run: |
          mkdir -p traefik/data/traefik
          cp -r .github/workflows/config/cert traefik/data/traefik/
      -
        name: "Service: Restart with Traefik"
        run: |
          ./composition.sh up --no-ports traefik
          ./composition.sh down,up --no-ports ${TARGET_SERVICE}
      -
        name: "Service: Wait"
        run: |
          sleep ${TARGET_TIMEOUT}s ; sleep ${TARGET_TIMEOUT}s
      -
        name: "Service: Test with Traefik"
        run: |
          if ! ./composition.sh check ${TARGET_SERVICE} traefik; then
            docker ps
            cd ${TARGET_SERVICE} ; docker-compose logs
            cd traefik ; docker-compose logs
            exit 1
          fi
          cd netdata
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || (docker ps ; docker-compose logs ; exit 1)
          cd ../traefik
          docker-compose exec -T traefik wget --spider --no-check-certificate https://localhost:9443/netdata/ \
            || (docker ps ; docker-compose logs ; cd ../netdata ; docker-compose logs ; exit 1)
