name: "Self Test Script"

on:
  pull_request:
    branches: master
  push:
    branches: master

env:
  DEBUG: 1

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-24.04 , ubuntu-24.04-arm ]
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v4
      -
        name: "Run: Test Script"
        run: _scripts/test_comp.sh
