name: "Self Test Script"

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v4
      -
        name: "Run: Test Script"
        run: _scripts/test_comp.sh
