version: '2.4'

services:
  i2p:
    hostname: i2p
    image: padhihomelab/i2p:1.7.0
    restart: unless-stopped

    volumes:
    - ./data/i2p/i2p/.i2p:/i2p/.i2p
    - ./data/i2p/i2psnark:/i2psnark

    environment:
      TZ: ${TZ:?}
      DOCKER_UID: ${USER_ID:?}
