version: '2.4'

services:
  i2p:
    ports:
    - 4444:4444       # HTTP Proxy
    - 4445:4445       # HTTPS Proxy
    - 6668:6668       # IRC Proxy
    - 7654:7654       # I2CP
    - 7656:7656       # SAM Bridge
    - 7657:7657       # Router Console
    - 7658:7658       # I2P Site
    - 7659:7659       # SMTP Proxy
    - 7660:7660       # POP3 Proxy
    - 7652:7652       # UPnP
    - 7653:7653/udp   # UPnP
    - 12345:12345     # I2NP
    - 12345:12345/udp # I2NP
    environment:
      JVM_XMX: 768m
